experiment:
    dataset: IRIS
    model: FF
    lr_sched:
    criterion: CrossEntropyLoss
    batch_size: 10
    epoch_bounds: [3, 10]
    subset_bounds: [0.2, 1]
    use_checkpoints: True
    shuffle: False
    only_train_on_new: False
fidelity:
    epoch: [10]
    data_subset_ratio: [0.2, 0.4, 0.6, 0.8, 1]
configuration:
    lr: [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6]
    momentum: [0.1]
    optimizer: [SGD, Adam]
plot:
    vis_method: [trade_off, grid]
    results_file_name: true_false_false

