experiment:
    dataset: IRIS
    model: FF
    lr_sched:
    criterion: CrossEntropyLoss
    batch_size: 10
    epoch_bounds: [3, 10]
    subset_bounds: [0.4, 1]
    use_checkpoints: False
    shuffle: False
    only_train_on_new: False
    d_sub: 2
    step_scaling: exponential
    seed: 100
fidelity:
    epoch: [10]
    data_subset_ratio:
configuration:
    lr: [0.00025, 0.0005, 0.00075, 0.001, 0.00125]
    momentum: [0.1, 0.3, 0.6]
    optimizer: [SGD, Adam]
plot:
    vis_method: []
    results_file_name: no_checkpoint

